### ISSUE TITLE
drowning is misspelt

### ISSUE THREAD

**Issue by JoelLucaAdams** [owoalex/uwu-inator#2]
@owoalex 

https://github.com/owoalex/uwu-inator/blob/8c9201df5188949ae1bb642bb647c24fa9015f00/output.txt#L8

1. It should say "dwowning", not "drowning". Very disappointed in this, please do better next time.

Kind Regards,

uwu

**Comment by itsmichaelwest** [comment]
+1

**Comment by itsmichaelwest** [comment]
Could we get an ETA on a fix?

**Comment by habaldwin01** [comment]
fixed issue ❤️
